previewsEnabled: true

services:
  - type: web
    name: iac-test-3
    env: node
    repo: https://github.com/hieurender/express-3
    buildCommand: yarn
    startCommand: node app.js
    envVars:
      - fromGroup: prod-vars-1
        previewGroup: staging-vars-1
  - type: web
    name: static-iac
    env: static
    buildCommand: yarn build
    staticPublishPath: ./build
    repo: https://github.com/hieurender/create-react-app
    branch: master
