previewsEnabled: true

services:
  - type: web
    name: iac-test-3
    env: node
    repo: https://github.com/hieurender/express-hello-world
    buildCommand: yarn
    startCommand: node app.js
    envVars:
      # Will not be copied!
      # Value for MY_API_KEY provided in dashboard will not be copied to preview environments
      - key: MY_API_KEY
        sync: false
      # Will be copied
      # USER_PROVIDED_SECRET will be copied to preview environments
      - fromGroup: all-settings-2

envVarGroups:
- name: all-settings-2
  envVars:
    - key: USER_PROVIDED_SECRET
      sync: false
